### ISSUE TITLE
few issues I noticed

### ISSUE THREAD

**Issue by futureproof123** [lunaprey/newworldfishbot#1]
the 'hook indicator' ui element isn't being detected sometimes, causing the bot to continue to cast over and over
also
sometimes the bot continues to reel in the fish until the line snaps

playing 1920x1080 resolution, fished in everfall near the old man

**Comment by lunaprey** [comment]
> the 'hook indicator' ui element isn't being detected sometimes, causing the bot to continue to cast over and over
> also
> sometimes the bot continues to reel in the fish until the line snaps
> 
> playing 1920x1080 resolution, fished in everfall near the old man

Thank you for your interest in my bot. I agree it's nowhere near ready at the moment. I have some updates intended for day. Hopefully they will improve things a bit!

**Comment by lunaprey** [comment]
I will leave this ticket open until I feel confident it is resolved.

**Comment by lunaprey** [comment]
Bot has greatly been improved. Give it a try now. I think you will see greatly improved results.

Note: Use CTRL ALT Z to launch bot in game and ESC to exit app.
